export const phoneUsers = [
  {
    phone: "0900800901",
    status: "active",
    type: "TrueMove H",
    name: "สมชาย ทองสุข",
    grading: "blue",
    idno: "xxxxxxxxx0123",
    trueno: "1234567890",
    subtype: "PRE",
    scoring: "สามารถขายทำการขายได้",
    arpa: "THB 15.00",
    empowerment: "เกรด B | วงเงินต่อปี 1500",
  },
  {
    phone: "0912345678",
    status: "inactive",
    type: "AIS",
    name: "สุรีย์พร ทองใบ",
    grading: "yellow",
    idno: "xxxxxxxxx0456",
    trueno: "9876543210",
    subtype: "POST",
    scoring: "ไม่สามารถขายทำการขายได้",
    arpa: "THB 10.00",
    empowerment: "เกรด D | วงเงินต่อปี 500",
  },
  {
    phone: "0923456789",
    status: "active",
    type: "TrueMove H",
    name: "ธนาธิป เมธาวี",
    grading: "red",
    idno: "xxxxxxxxx0678",
    trueno: "1122334455",
    subtype: "PRE",
    scoring: "สามารถขายทำการขายได้",
    arpa: "THB 25.00",
    empowerment: "เกรด A | วงเงินต่อปี 2000",
  },
  {
    phone: "0934567890",
    status: "inactive",
    type: "AIS",
    name: "ภาคิน คำภา",
    grading: "green",
    idno: "xxxxxxxxx0890",
    trueno: "5566778899",
    subtype: "POST",
    scoring: "สามารถขายทำการขายได้",
    arpa: "THB 20.00",
    empowerment: "เกรด B | วงเงินต่อปี 1200",
  },
  {
    phone: "0945678901",
    status: "active",
    type: "TrueMove H",
    name: "พีระนาคิน ไวตระกูล",
    grading: "green",
    idno: "xxxxxxxxx0213",
    trueno: "1969459392",
    subtype: "PRE",
    scoring: "สามารถขายทำการขายได้",
    arpa: "THB 23.33",
    empowerment: "เกรด C | วงเงินต่อปี 1000",
  },
  {
    phone: "0956789012",
    status: "inactive",
    type: "TrueMove H",
    name: "อัญชลี อุดม",
    grading: "blue",
    idno: "xxxxxxxxx1324",
    trueno: "3344556677",
    subtype: "POST",
    scoring: "สามารถขายทำการขายได้",
    arpa: "THB 30.00",
    empowerment: "เกรด B | วงเงินต่อปี 1500",
  },
  {
    phone: "0967890123",
    status: "active",
    type: "AIS",
    name: "วรากร ชัยมงคล",
    grading: "purple",
    idno: "xxxxxxxxx1456",
    trueno: "1231231234",
    subtype: "PRE",
    scoring: "สามารถขายทำการขายได้",
    arpa: "THB 28.00",
    empowerment: "เกรด A | วงเงินต่อปี 1800",
  },
  {
    phone: "0978901234",
    status: "inactive",
    type: "TrueMove H",
    name: "อัญญา สุทธิสาร",
    grading: "green",
    idno: "xxxxxxxxx1578",
    trueno: "4325436543",
    subtype: "POST",
    scoring: "สามารถขายทำการขายได้",
    arpa: "THB 22.50",
    empowerment: "เกรด C | วงเงินต่อปี 1100",
  },
  {
    phone: "0989012345",
    status: "active",
    type: "AIS",
    name: "ภูริทัต เชื้อผา",
    grading: "blue",
    idno: "xxxxxxxxx2345",
    trueno: "7654321987",
    subtype: "PRE",
    scoring: "สามารถขายทำการขายได้",
    arpa: "THB 18.00",
    empowerment: "เกรด B | วงเงินต่อปี 1600",
  },
  {
    phone: "0990123456",
    status: "inactive",
    type: "TrueMove H",
    name: "ภูมิภัทร์ ราชทิน",
    grading: "yellow",
    idno: "xxxxxxxxx2456",
    trueno: "9876543123",
    subtype: "POST",
    scoring: "สามารถขายทำการขายได้",
    arpa: "THB 27.00",
    empowerment: "เกรด C | วงเงินต่อปี 1300",
  },
];

export function findPhone(phone) {
  return phoneUsers.find((user) => user.phone === phone);
}

export function filterPhones(status, foundPhones) {
  if (status === "ALL") {
    return foundPhones; // แสดงข้อมูลทั้งหมดเมื่อเลือก ALL
  } else {
    return foundPhones.filter((user) => user.status === status); // กรองตามสถานะ
  }
}
